development:
  adapter: postgresql
  database: todolist_database
  pool: 5
  username: user1
  password: userpass
  timeout: 5000
test:
  adapter: postgresql
  database: todolist_database
  pool: 5
  username: user1
  password: userpass
  timeout: 5000

production:
  adapter: postgresql
  database: todolist_database
  pool: 5
  username: user1
  password: userpass
  timeout: 5000
